apiVersion: v1
kind: Service
metadata:
  name: expensetracker-service
  namespace: expense-tracker
spec:
  type: LoadBalancer
  selector:
    app: expensetracker
  ports:
    - port: 80
      targetPort: 8000

